services:
  webar_proto:
    build:
      context: .
      dockerfile: Dockerfile.webar
    ports:
      - "8080:80" # 8080 ist der Port auf dem Host, 80 ist der Port im Container
    restart: unless-stopped
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - "8081:80"
    environment:
      DB_HOST: postgres
      DB_PORT: 5444
      DB_NAME: webar
      DB_USER: webar_user
      DB_PASS: webar_pass
    depends_on:
      - postgres
    restart: unless-stopped
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: webar
      POSTGRES_USER: webar_user
      POSTGRES_PASSWORD: webar_pass
    ports:
      - "5444:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  pgdata:
