name: Build & Deploy Docker

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via Compose
        run: |
          docker compose up -d --build
